config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from exuser.views import register

urlpatterns = [
    path('', include('exuser.urls')),
    url(r'^auth/', include('djoser.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('exuser.urls')),
    path('api/v1/', include('djoser.urls.jwt')),
]

exuser/urls.py
from django.urls import path

from exuser import views

app_name = 'exuser'

urlpatterns = [
    path('', views.register, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('register', views.register, name='register'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),
]

exuser/models.py
import random

from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
import exuser.constants as _const


class MyExUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, username, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        color = random.choice(_const.AVA_COLORS)
        return self._create_user(email, username, password, color_avatar=color, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        color = random.choice(_const.AVA_COLORS)
        return self._create_user(username, email, password, color_avatar=color, **extra_fields)


# Create your user models here.

class ExUser(AbstractUser):
    email = models.EmailField(blank=True, null=True, max_length=255, unique=True)
    username = models.CharField(blank=True, null=True, max_length=255, unique=False)
    color_avatar = models.CharField(blank=True, null=True, max_length=255, unique=False)
    device_id = models.CharField(blank=True, null=True, max_length=255)
    is_baned = models.BooleanField(default=False)

    objects = MyExUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        db_table = 'tbl_exuser'

    def __str__(self):
        return self.email

    def __unicode__(self):
        return self.email


class UserProfile(models.Model):
    GENDERS = (
        (_const.OTHER, _const.OTHER),
        (_const.MALE, _const.MALE),
        (_const.FEMALE, _const.FEMALE)
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    address = models.CharField(max_length=255, blank=True)
    photo = models.ImageField(upload_to='uploads', blank=True)
    gender = models.CharField(max_length=20, choices=GENDERS, default=_const.OTHER)
    phone = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        db_table = 'tbl_user_profile'

exuser/forms.py
from django import forms
from django.contrib.auth import authenticate
from rest_framework.exceptions import APIException

from exuser.models import ExUser


class AuthUserFrom(forms.Form):
    email = forms.EmailField(label='Email', max_length=150,
                             widget=forms.TextInput(attrs={'autofocus': True,}),
                             error_messages={'invalid': 'Invalid email', 'required': 'Require email'})
    password = forms.CharField(label="Password", strip=False,
                               widget=forms.PasswordInput(
                                   attrs={}),
                               error_messages={'invalid': 'Invalid password', 'required': 'Require password'})
    remember_me = forms.BooleanField(widget=forms.CheckboxInput, required=False)

    error_messages = {
        'invalid_login': "Email hoặc mật khẩu không chính xác",
        'inactive': "Tài khoản của bạn đã bị khoá!",
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            try:
                self.user_cache = authenticate(self.request, email=email, password=password)
            except Exception as e:
                if isinstance(e, APIException):
                    pass
                else:
                    raise e
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'email': email})
            else:
                user = ExUser.objects.get(id=self.user_cache.id, is_active=1)
                if not user:
                    raise forms.ValidationError(
                        self.error_messages['inactive'],
                        code='inactive',
                        params={'email': self.email})

            return self.cleaned_data

    def get_user(self):
        return self.user_cache

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

exuser/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse_lazy

from exuser.forms import AuthUserFrom


def register(request):
    return render(request, 'exuser/register.html')


@login_required(login_url='/account/login')
def dashboard(request):
    if request.method == 'GET':
        return render(request, 'exuser/index.html')
    else:
        pass


def logout_view(request):
    logout(request)
    return redirect('exuser:login')


class Login(LoginView):
    form_class = AuthUserFrom
    template_name = 'exuser/login.html'

    def get(self, request, *args, **kwargs):
        if request.session.get_expiry_age() > 0:
            if request.user.is_authenticated:
                return redirect('exuser:dashboard')
            else:
                logout(request)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        remember_me = form.cleaned_data['remember_me']
        if remember_me:
            self.request.session.set_expiry(60 * 60 * 24 * 30)
        else:
            self.request.session.set_expiry(0)
        return super(Login, self).form_valid(form)

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form})

    def get_success_url(self):
        self.success_url = reverse_lazy('exuser:dashboard')
        return self.success_url

templates/exuser/base.html
{% load static %}
{#{% load widget_tweaks %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- loader-->
    <link href="{% static 'assets/css/pace.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'assets/js/pace.min.js' %}"></script>
    <!--favicon-->
    <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">
    <!-- Vector CSS -->
    <link href="{% static 'assets/plugins/vectormap/jquery-jvectormap.min.css' %} " rel="stylesheet"/>
    <!-- simplebar CSS-->
    <link href="{% static 'assets/plugins/simplebar/css/simplebar.css' %}" rel="stylesheet"/>
    <!-- Bootstrap core CSS-->
    <link href="{% static 'assets/css/bootstrap.min.css' %} " rel="stylesheet"/>
    <!-- animate CSS-->
    <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Icons CSS-->
    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Sidebar CSS-->
    <link href="{% static 'assets/css/sidebar-menu.css' %}" rel="stylesheet"/>
    <!-- Custom Style-->
    <link href="{% static 'assets/css/app-style.css' %}" rel="stylesheet"/>

</head>

<body class="bg-theme bg-theme1">

<!-- Start wrapper-->
<div id="wrapper">

    <!--Start sidebar-wrapper-->
    {% include "exuser/sidebar.html" %}
    <!--End sidebar-wrapper-->

    <!--Start topbar header-->
    {% include "exuser/top-nav.html" %}
    <!--End topbar header-->

    <div class="clearfix"></div>

    {% block content %}{% endblock %}
    <!--End content-wrapper-->
    <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->

    <!--Start footer-->
    <footer class="footer">
        <div class="container">
            <div class="text-center">
                Copyright © 2018 Dashtreme Admin
            </div>
        </div>
    </footer>
    <!--End footer-->

    <!--start color switcher-->
    <div class="right-sidebar">
        <div class="switcher-icon">
            <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
        </div>
        <div class="right-sidebar-content">

            <p class="mb-0">Gaussion Texture</p>
            <hr>

            <ul class="switcher">
                <li id="theme1"></li>
                <li id="theme2"></li>
                <li id="theme3"></li>
                <li id="theme4"></li>
                <li id="theme5"></li>
                <li id="theme6"></li>
            </ul>

            <p class="mb-0">Gradient Background</p>
            <hr>

            <ul class="switcher">
                <li id="theme7"></li>
                <li id="theme8"></li>
                <li id="theme9"></li>
                <li id="theme10"></li>
                <li id="theme11"></li>
                <li id="theme12"></li>
                <li id="theme13"></li>
                <li id="theme14"></li>
                <li id="theme15"></li>
            </ul>

        </div>
    </div>
    <!--end color switcher-->

</div><!--End wrapper-->

<!-- Bootstrap core JavaScript-->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

<!-- simplebar js -->
<script src="{% static 'assets/plugins/simplebar/js/simplebar.js' %}"></script>
<!-- sidebar-menu js -->
<script src="{% static 'assets/js/sidebar-menu.js' %}"></script>
<!-- loader scripts -->
<script src="{% static 'assets/js/jquery.loading-indicator.js' %}"></script>
<!-- Custom scripts -->
<script src="{% static 'assets/js/app-script.js' %}"></script>
<!-- Chart js -->

<script src="{% static 'assets/plugins/Chart.js/Chart.min.js' %}"></script>

<!-- Index js -->
<script src="{% static 'assets/js/index.js' %}"></script>
{% block pagejs %}
{% endblock %}
</body>
</html>

templates/exuser/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Đăng nhập</title>
    <!-- loader-->
    <link href="{% static 'assets/css/pace.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'assets/js/pace.min.js' %}"></script>
    <!--favicon-->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" type="image/png">
    <!-- Bootstrap core CSS-->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <!-- animate CSS-->
    <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Icons CSS-->
    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Custom Style-->
    <link href="{% static 'assets/css/app-style.css' %}" rel="stylesheet"/>

</head>

<body class="bg-theme bg-theme1">

<!-- start loader -->
<div id="pageloader-overlay" class="visible incoming">
    <div class="loader-wrapper-outer">
        <div class="loader-wrapper-inner">
            <div class="loader"></div>
        </div>
    </div>
</div>
<!-- end loader -->

<!-- Start wrapper-->
<div id="wrapper">

    <div class="loader-wrapper">
        <div class="lds-ring">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <div class="card card-authentication1 mx-auto my-5">
        <div class="card-body">
            <div class="card-content p-2">
                <div class="text-center">
                    <img src="{% static 'assets/images/logo-icon.png' %}" alt="logo icon">
                </div>
                <div class="card-title text-uppercase text-center py-3">Đăng nhập</div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        <label for="exampleInputUsername" class="sr-only">Username</label>
                        <div class="position-relative has-icon-right">

                            {{ form.email|add_class:'form-control input-shadow'|attr:'type:text'|attr:'placeholder:Tên đăng nhập/email'|attr:'v-model:exUser.email' }}

                            <div class="form-control-position">
                                <i class="icon-user"></i>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword" class="sr-only">Password</label>
                        <div class="position-relative has-icon-right">
                            {{ form.password|add_class:'form-control input-shadow'|attr:'type:password'|attr:'placeholder:Mật khẩu'|attr:'v-model:exUser.password' }}
                            <div class="form-control-position">
                                <i class="icon-lock"></i>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-6">
                            <div class="icheck-material-white">
                                <input type="checkbox" id="user-checkbox" checked=""/>
                                <label for="user-checkbox">Ghi nhớ đăng nhập</label>
                            </div>
                        </div>
                        <div class="form-group col-6 text-right">
                            <a href="reset-password.html">Quên mật khẩu</a>
                        </div>
                    </div>
                    {{ form.invalid_login }}
                    <button v-if="loading" type="submit" class="btn btn-light btn-block waves-effect waves-light"
                            disabled>
                        <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                        Đang đăng nhập...
                    </button>
                    <button v-else-if="exUser.email !== '' && exUser.password !== ''" type="submit"
                            class="btn btn-light btn-block">Đăng nhập
                    </button>
                    <button v-else type="submit"
                            class="btn btn-light btn-block" disabled>Đăng nhập
                    </button>
                    <div class="text-center mt-3">Hoặc</div>

                    <div class="form-row mt-4">
                        <div class="form-group mb-0 col-6">
                            <button type="button" class="btn btn-light btn-block"><i class="fa fa-facebook-square"></i>
                                Facebook
                            </button>
                        </div>
                        <div class="form-group mb-0 col-6 text-right">
                            <button type="button" class="btn btn-light btn-block"><i class="fa fa-twitter-square"></i>
                                Twitter
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <div class="card-footer text-center py-3">
            <p class="text-warning mb-0">Bạn chưa có account? <a href="{% url 'exuser:register' %}"> Đăng ký tại đây</a>
            </p>
        </div>
    </div>

    <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->

    <!--start color switcher-->
    <div class="right-sidebar">
        <div class="switcher-icon">
            <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
        </div>
        <div class="right-sidebar-content">

            <p class="mb-0">Gaussion Texture</p>
            <hr>

            <ul class="switcher">
                <li id="theme1"></li>
                <li id="theme2"></li>
                <li id="theme3"></li>
                <li id="theme4"></li>
                <li id="theme5"></li>
                <li id="theme6"></li>
            </ul>

            <p class="mb-0">Gradient Background</p>
            <hr>

            <ul class="switcher">
                <li id="theme7"></li>
                <li id="theme8"></li>
                <li id="theme9"></li>
                <li id="theme10"></li>
                <li id="theme11"></li>
                <li id="theme12"></li>
                <li id="theme13"></li>
                <li id="theme14"></li>
                <li id="theme15"></li>
            </ul>

        </div>
    </div>
    <!--end color switcher-->

</div><!--wrapper-->

<!-- Bootstrap core JavaScript-->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

<!-- sidebar-menu js -->
<script src="{% static 'assets/js/sidebar-menu.js' %}"></script>

<!-- Custom scripts -->
<script src="{% static 'assets/js/app-script.js' %}"></script>

<script src="{% static 'assets/js/vue.js' %}"></script>
<script src="{% static 'assets/js/vue-resource.js' %}"></script>
<script src="{% static 'assets/js/pages/login.js' %}"></script>


</body>
</html>

templates/exuser/sidebar.html
{% load static %}
<!--Start sidebar-wrapper-->
<div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
    <div class="brand-logo">
        <a href="index.html">
            <img src="{% static 'assets/images/logo-icon.png'%}" class="logo-icon" alt="logo icon">
            <h5 class="logo-text">Dashtreme Admin</h5>
        </a>
    </div>
    <ul class="sidebar-menu do-nicescrol">
        <li class="sidebar-header">MAIN NAVIGATION</li>
        <li>
            <a href="index.html">
                <i class="zmdi zmdi-view-dashboard"></i> <span>Dashboard</span>
            </a>
        </li>

        <li>
            <a href="icons.html">
                <i class="zmdi zmdi-youtube"></i> <span>YouTube</span>
            </a>
        </li>

        <li>
            <a href="forms.html">
                <i class="zmdi zmdi-facebook"></i> <span>Facebook</span>
            </a>
        </li>

        <li>
            <a href="tables.html">
                <i class="zmdi zmdi-instagram"></i> <span>Instagram</span>
            </a>
        </li>

    </ul>

</div>
<!--End sidebar-wrapper-->

templates/exuser/top-nav.html
<header class="topbar-nav">
        <nav class="navbar navbar-expand fixed-top">
            <ul class="navbar-nav mr-auto align-items-center">
                <li class="nav-item">
                    <a class="nav-link toggle-menu" href="javascript:void();">
                        <i class="icon-menu menu-icon"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <form class="search-bar">
                        <input type="text" class="form-control" placeholder="Enter keywords">
                        <a href="javascript:void();"><i class="icon-magnifier"></i></a>
                    </form>
                </li>
            </ul>

            <ul class="navbar-nav align-items-center right-nav-link">
                <li class="nav-item dropdown-lg">
                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown"
                       href="javascript:void();">
                        <i class="fa fa-envelope-open-o"></i></a>
                </li>
                <li class="nav-item dropdown-lg">
                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown"
                       href="javascript:void();">
                        <i class="fa fa-bell-o"></i></a>
                </li>
                <li class="nav-item language">
                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown"
                       href="javascript:void();"><i class="fa fa-flag"></i></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-item"><i class="flag-icon flag-icon-gb mr-2"></i> English</li>
                        <li class="dropdown-item"><i class="flag-icon flag-icon-fr mr-2"></i> French</li>
                        <li class="dropdown-item"><i class="flag-icon flag-icon-cn mr-2"></i> Chinese</li>
                        <li class="dropdown-item"><i class="flag-icon flag-icon-de mr-2"></i> German</li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
                        <span class="user-profile"><img src="https://via.placeholder.com/110x110" class="img-circle"
                                                        alt="user avatar"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-item user-details">
                            <a href="javaScript:void();">
                                <div class="media">
                                    <div class="avatar"><img class="align-self-start mr-3"
                                                             src="https://via.placeholder.com/110x110"
                                                             alt="user avatar"></div>
                                    <div class="media-body">
                                        <h6 class="mt-2 user-title">Sarajhon Mccoy</h6>
                                        <p class="user-subtitle">mccoy@example.com</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li class="dropdown-item"><i class="icon-envelope mr-2"></i> Inbox</li>
                        <li class="dropdown-divider"></li>
                        <li class="dropdown-item"><i class="icon-wallet mr-2"></i> Account</li>
                        <li class="dropdown-divider"></li>
                        <li class="dropdown-item"><i class="icon-settings mr-2"></i> Setting</li>
                        <li class="dropdown-divider"></li>
                        <li class="dropdown-item"><a href="{% url 'exuser:logout' %}"><i class="icon-power mr-2"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>